# Generated by Django 4.0.4 on 2022-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(1, 'Mental Health'), (2, 'Heart Disease')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
