# Generated by Django 4.0.4 on 2022-08-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(1, 'Mental Health'), (2, 'Heart Disease'), (3, 'Covid19'), (4, 'Immunization')], max_length=10),
        ),
    ]
