# Generated by Django 4.0.4 on 2022-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_summary_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('Mental Health', 'Mental Health'), (2, 'Heart Disease'), (3, 'Covid19'), (4, 'Immunization')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
